In [32]:
import numpy as np

In [14]:
#Question 1

y=int(input("Donner un nombre de ligne :"))
z=int(input("Donner un nombre de colonne :"))
x=int(input("Donner le nombre de liste :"))
a=np.arange(x).reshape(y,z) #np.arange : nombre de liste #reshape: 9adeh mn ligne(y)-9adeh men colonne(z)|
b=a.tolist() # bech tbadel a l liste
print(b)


Donner un nombre de ligne :2
Donner un nombre de colonne :2
Donner le nombre de liste :4
[[0, 1], [2, 3]]


In [ ]:
#Question 2

y=int(input("Donner un nombre de ligne :"))
z=int(input("Donner un nombre de colonne :"))
x=int(input("Donner le nombre de liste :"))
a=np.arange(x).reshape(y,y)
print(a)
A=np.trace(b)# tejma3 diagonal
print(A)

In [37]:
#Question 3
import numpy as np
y=np.array([[1,2],[6,4],[3,5]])
x=int(input("the number of comparing :"))
for i in y :
    for a in i :
        if a>x :
            print(a)

the number of comparing :3
6
4


In [27]:
#Question 4

x=np.array([[8,9],[5,7],[1,2]])
y=np.array([[1,2],[6,4],[3,5]])
z=x+y
print(z)

[[ 9 11]
 [11 11]
 [ 4  7]]


In [30]:
#Question 5
e=int(input("Donner un nombre de ligne :"))
z=int(input("Donner un nombre de colonne :"))
x=int(input("Donner le debut  :"))
w=int(input("Donner la fin de l'intervalle :"))
a=np.random.randint(x,w,size=(e,z)) # tkharej a3ded bin x and w 
for i in a:
    print(i)
    y=i.mean()
    print("la moyenne est :",y)
    for j in i:
        V=j-y
        print("V=",V)
        
    

Donner un nombre de ligne :5
Donner un nombre de colonne :4
Donner le debut  :2
Donner la fin de l'intervalle :10
[7 2 6 4]
la moyenne est : 4.75
V= 2.25
V= -2.75
V= 1.25
V= -0.75
[6 6 3 2]
la moyenne est : 4.25
V= 1.75
V= 1.75
V= -1.25
V= -2.25
[9 2 6 7]
la moyenne est : 6.0
V= 3.0
V= -4.0
V= 0.0
V= 1.0
[4 8 9 7]
la moyenne est : 7.0
V= -3.0
V= 1.0
V= 2.0
V= 0.0
[3 3 4 2]
la moyenne est : 3.0
V= 0.0
V= 0.0
V= 1.0
V= -1.0
